### PR TITLE
Add undocumented shipingType.

### PR DESCRIPTION
**Pull request by Amurmurmur**

### CODE REVIEW

**Comment by isnifer** [comment]
@Amurmurmur please add `shippingType` here https://github.com/tipsi/tipsi-stripe/blob/master/src/utils/types.js#L49 too

**Comment by Amurmurmur** [comment]
@isnifer Done sir!

**Comment by isnifer** [comment]
@Amurmurmur you wrote in docs in `html` — you should do it in `.md` file because `.html-files` are autogenerated.
You wrote "default value for `shippingType` is `shipping`. Available options are: `delivery` | `store_pickup` | `service_pickup`". So, it means `shippingType` is:
```js
PropTypes.oneOf(['shipping', 'delivery', 'store_pickup', 'service_pickup'])
```
Not just:
```js
PropTypes.string
```

**Comment by isnifer** [comment]
@Amurmurmur 
```sh
npm run start-docs
```
Open localhost:3000
Edit `website/docs-md/paymentrequestwithapplepayitemsoptions.md`
```sh
# upgrade existing docs website in repo
npm run build-docs
```

**Comment by isnifer** [comment]
@Amurmurmur also, please, describe what this `shippingType` does instead of `Shipping type string`.

**Comment by Amurmurmur** [comment]
@isnifer All sorted sir

**Pull request merged**
