### PR TITLE
Fixed issue when specifying countryCode

### PR DESCRIPTION
**Pull request by mckn**
This resolves the following issue: #201

### CODE REVIEW

**Comment by isnifer** [comment]
Nice, thank you!

**Comment by mckn** [comment]
Is it possible to get this released quickly?

**Comment by isnifer** [comment]
@mckn yes, sure. Just wait tests

**Comment by mckn** [comment]
cool, thanks! awesome response!

**Comment by isnifer** [comment]
@mckn, for now, you can check it yourself if set in package.json:
```json
"tipsi-stripe": "tipsi/tipsi-stripe#1392525"
```

**Pull request merged**
