### PR TITLE
Fix V6 iOS lock

### PR DESCRIPTION
**Pull request by bramski**
## Proposed changes
This rebases the original pull request https://github.com/tipsi/tipsi-stripe/pull/418
So that it can be merged onto modern 7.5.1 which includes support for RN 0.59.  If @theohdv can't finish the work on the original PR I will take over and get this merged.

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [X] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [ ] I know that my PR will be merged only if it has tests and they pass  
- [X] There is no test that can hit this as it only reproduces on a real device.

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by fbartho** [comment]
If you need to hot-patch this issue, you can run this script in your `npm postinstall`

```javascript
const fs = require("fs");
const path = require("path");
const iOSFieldPath = path.join(moduleDir, "ios", "TPSStripe", "TPSCardField.m");

// Patch the iOS Field wrapper so until tipsi fixes: https://github.com/tipsi/tipsi-stripe/issues/408
	const iOSFieldSource = fs.readFileSync(iOSFieldPath).toString();
	fs.writeFileSync(
		iOSFieldPath,
		iOSFieldSource
			.replace(/\)dealloc/, ")tr_disabled_dealloc")
			.replace(
				/UIKeyboardWillShowNotification/g,
				`@"TR_DISABLED_KEYBOARD_WILL_SHOW"`,
			),
	);
```

**Comment by theohdv** [comment]
Thanks @bramski, indeed i won't finish the work because i don't really have the time as we are not using this lib anymore in our project.

**Comment by macnibblet** [comment]
What's the timeline on getting this merged, this fixes a problem with 7.5.1 and 12.4 on iOS for me. 
The app crashes as soon as you touch the PaymentCardField

**Comment by hjhart** [comment]
Patch provided by @fbartho worked great for us in the interim. Thank you!

**Comment by fbartho** [comment]
Closing this PR because the fix is already included in the 8.0 release branch (`experimental`) -- please test the `8.0.0-beta.6` or later!

**Comment by tvhimanshu** [comment]
> If you need to hot-patch this issue, you can run this script in your `npm postinstall`
> 
> ```js
> const fs = require("fs");
> const path = require("path");
> const moduleDir = path.resolve("./node_modules"); // Edit this to match wherever you put the script
> const iOSFieldPath = path.join(moduleDir, "ios", "TPSStripe", "TPSCardField.m");
> 
> // Patch the iOS Field wrapper so until tipsi fixes: https://github.com/tipsi/tipsi-stripe/issues/408
> 	const iOSFieldSource = fs.readFileSync(iOSFieldPath).toString();
> 	fs.writeFileSync(
> 		iOSFieldPath,
> 		iOSFieldSource
> 			.replace(/\)dealloc/, ")tr_disabled_dealloc")
> 			.replace(
> 				/UIKeyboardWillShowNotification/g,
> 				`@"TR_DISABLED_KEYBOARD_WILL_SHOW"`,
> 			),
> 	);
> ```

Build input file cannot be found: **'/node_modules/tipsi-stripe/ios/TPSStripe/TPSStripeManager+Constants.m'**

Above error is coming

**Pull request closed without merging**
