### PR TITLE
assigned promiseRejector in api calls to createTokenWithBankAccount a…

### PR DESCRIPTION
**Pull request by andyboythekid**
## Proposed changes
Fixes for the createTokenWithBankAccount and createTokenWithCard. These two methods currently fail silently because the rejection block is not assigned. 

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
- [] I have added tests that prove my fix is useful or that my feature works  
- [x] I have added necessary documentation (if appropriate)  
- [x] I know that my PR will be merged only if it has tests and they pass

### CODE REVIEW

**Comment by cybergrind** [comment]
Hi @andyboythekid! Thank you for your contribution. It looks similar to #377 and maybe it worth to put everything together because I can see there `promiseResolver = resolve;`
And we will need a test for it. Maybe we can just reproduce issue from #372 for that?

**Comment by mattfordham** [comment]
Any chance this might land soon?

And FYI @andyboythekid - Looks like the tests are within the `example` directory: https://github.com/tipsi/tipsi-stripe/tree/master/example/__tests__

**Comment by cybergrind** [comment]
Fixed in #422

**Comment by pmatheusvinhas** [comment]
Hi guys. I'm facing that problem with Android on August/2020.

**Comment by pmatheusvinhas** [comment]
Hi guys. I'm facing that problem with Android on August/2020 but in 'createTokenWithCard'.

**Comment by pmatheusvinhas** [comment]
Hi guys. I'm facing that problem with Android on August/2020.

**Pull request closed without merging**
