### PR TITLE
Point users to @stripe/stripe-react-native, and add deprecation notices to: library, readme, docs, CLI

### PR DESCRIPTION
**Pull request by mikeb-stripe**
This PR points users of tipsi-stripe to the official Stripe react-native library, [@stripe/stripe-react-native](https://github.com/stripe/stripe-react-native). 

This happens in a few places
- The README.md for this repo
- The docs site for tipsi-stripe
- As a `console.warn` message on the CLI
- As a `console.warn` message on postinstall of the npm library

I did not update the version number for the NPM library, or PR/Issue templates for github.

Ideally, it would be great if we could also:

- [ ] agree on a plan / time / date to [Archive this library on GitHub](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)
- [ ] message users in the tipsi-stripe discord about migrating to the official library
- [ ] create a [pinned issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) on this repo pointing devs to the official library

### CODE REVIEW

**Comment by cybergrind** [comment]
hi @mikeb-stripe !
Sounds great!

**Comment by cybergrind** [comment]
@mikeb-stripe regarding archiving, probably we could wait some time until everyone migrated.

It looks like some people still have to use it because they cannot upgrade RN version. So they will have at least some place to discuss their struggles :)

**Comment by mikeb-stripe** [comment]
Thanks for the help @cybergrind. Can you also run `npm deprecate` at some point? Looks like that will be helpful for folks who `npm install` projects with tipsi-stripe - [docs are here](https://docs.npmjs.com/cli/v8/commands/npm-deprecate).

Maybe with a message like:

> tipsi-stripe is no longer maintained. Please migrate your project to @stripe/stripe-react-native: https://github.com/stripe/stripe-react-native

**Comment by cybergrind** [comment]
@mikeb-stripe I've done this. 

now it has been removed from search. 
there are still some other forks without clear deprecation, but probably at this point it doesn't matter

**Comment by mikeb-stripe** [comment]
image


Looks good, thank you! I'll spend some time looking through other forks to see what's out there. Appreciate your help @cybergrind!

**Pull request merged**
