### PR TITLE
remove rnpm usage

### LINKED ISSUE #495: react-native 0.60 Remove "rnpm" config
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Upgraded our app to react-native 0.60
Run `npm start`

## Environment
* `tipsi-stripe` version: 0.7.5
* iOS or Android: All
* OS version: All
* React-Native version: 0.60

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

Screen Shot 2019-07-04 at 8 51 10 AM

### PR DESCRIPTION
**Pull request by bell-steven**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue.

"rnpm" is deprecated and support for it will be removed in next major version of the CLI.
This should close #495.

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [x] I know that my PR will be merged only if it has tests and they pass  

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by mgarabedian** [comment]
Any update on this rnpm fix being merged and released?

**Comment by jan-happy** [comment]
This would help a lot. Thank you!

**Comment by younes200** [comment]
please merge this !

**Comment by fbartho** [comment]
@bell-steven -- if you can change the base branch of this fix to #experimental -- I might be able to get this tested and merged into there soon.

**Comment by bell-steven** [comment]
Closed in favor of #618 as per @fbartho.

**Pull request closed without merging**
