### PR TITLE
Set iOS deployment target version to 8.0

### PR DESCRIPTION
**Pull request by sergeyzhukov**
Fix for https://github.com/tipsi/tipsi-stripe/issues/41 issue

### CODE REVIEW

**Comment by Nepherhotep** [comment]
@itsmepetrov is there any test checking the oldest/newest supporting os version?

**Comment by itsmepetrov** [comment]
@sergeyzhukov please update `Requirements` in `README.md`

**Comment by cybergrind** [comment]
@sergeyzhukov @itsmepetrov what's about testing on 8.0 device simulator?

**Comment by fabriziomoscon** [comment]
ios 10 adoption only reaches 88% according to Mixpanel. In my experience this number will not go higher, so this PR would allow to get to at least 98% I reckon.

screen shot 2017-05-19 at 11 23 24

**Pull request closed without merging**
