### PR TITLE
remove rnpm usage

### LINKED ISSUE #495: react-native 0.60 Remove "rnpm" config
## Before I have submitted the issue 
[ ] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[ ] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[ ] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[ ] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
Upgraded our app to react-native 0.60
Run `npm start`

## Environment
* `tipsi-stripe` version: 0.7.5
* iOS or Android: All
* OS version: All
* React-Native version: 0.60

## Screenshots, GIFs (Must to have)
Just drag-and-drop them to this textarea

Screen Shot 2019-07-04 at 8 51 10 AM

### LINKED ISSUE #635: Deprecated SDK issue
Loading dependency graph...warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - tipsi-stripe: https://github.com/tipsi/tipsi-stripe#readme

### LINKED ISSUE #652: Use deprecated "rnpm" config
## Before I have submitted the issue 
[x] I have read an [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html)  
[x] I know that for an iOS I need to install pods because I've read the [installation guide](https://tipsi.github.io/tipsi-stripe/docs/installation.html#cocoapods-ios)  
[x] I have read a [linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html) and checked that everything is OK like in [manual linking guide](https://tipsi.github.io/tipsi-stripe/docs/linking.html#manual)  
[x] I know that before using `tipsi-stripe` I need to set options for my app as described in [usage guide](https://tipsi.github.io/tipsi-stripe/docs/usage.html)  

## The problem
When running react-native link I get the following warning:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - tipsi-stripe: https://github.com/tipsi/tipsi-stripe#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
error Unknown dependency. Make sure that the package you are trying to link is already installed in your "node_modules" and present in your "package.json" dependencies. Run CLI with --verbose flag for more details.
```

Could you please solve this issue in next release.

## Environment
* `tipsi-stripe` version: 7.5.1
* iOS or Android: both
* React-Native version: 0.60.4

### PR DESCRIPTION
**Pull request by bell-steven**
Follow up PR from #557 as per [this comment](https://github.com/tipsi/tipsi-stripe/pull/557#issuecomment-589820584).

Closes #495
closes #635 
closes #652

### CODE REVIEW

**Comment by fbartho** [comment]
This looks good to me! Hopefully I'll be able to test this next week. (We're upgrading to react-native 0.62 from 0.59 in our company's app, so we just started getting this warning)

**Comment by robertmurray** [comment]
@fbartho this looks good to me!

**Comment by cdownard** [comment]
Bumping as Travis is currently failing

**Comment by fbartho** [comment]
@bell-steven  @ellidy @LRNZ09  -- or for anybody reading this:

What's the impact of moving the `rnpm` config? -- specifically, if we remove it will it drop support for react-native 0.59?

React-Native 0.6x is a pretty brutal upgrade, so I think we need to keep support for 0.59 if possible.

This is a deprecated but not removed configuration option.

**Comment by bell-steven** [comment]
@fbartho from what I understand, it would be a breaking change, and make the library incompatible with RN > 0.60.0.

Keeping the old `rnpm` config in the `package.json` and also adding the `react-native.config.js` should satisfy both.  See [this](https://github.com/react-native-community/cli/issues/346#issue-436246100) issue in the React Native CLI repo for reference. 

I can go ahead and update this PR if that is what makes sense, let me know.

**Comment by fbartho** [comment]
Thanks @bell-steven: that’s exactly the information we needed. Please do update the PR to support that backwards compatible option!

If you want, we can add the key `”#rnpm”: “delete this after dropping support for RN 0.59”` to the top level of package.json as a ”comment”.

Thoughts?

**Comment by bell-steven** [comment]
@fbartho updated.  

It doesn't do too much harm to leave it in, when support for RN 0.59 is dropped, it is not a big deal if it isn't removed...

**Comment by fbartho** [comment]
@bell-steven -- I don't know when we're going to spin the next beta. Do you have a time sensitive reason that I should try to firm up the date? or are you comfortable if I just commit that it will be in the next beta whenever we get around to shipping one? (I'd like to do that when there are a few more fixes/changes included, for example -- the automatic zip code field that stripe-ios is adding these days needs an API exposed around it)

**Comment by bell-steven** [comment]
@fbartho nope. Whenever it is released is fine. I'm actually still operating off the v7 releases. 

I can always `patch-package` this.

**Comment by allan-simon** [comment]
@bell-steven  do you have the patch-package instruction to do it locally ? :) 

@bell-steven can it be put in one of the beta , I'm in beta 10 and I don't see it :)

**Comment by debianw** [comment]
When this pull request is going to be approved ? When the next beta version is going to be released ?

**Pull request closed without merging**
