### PR TITLE
Alipay fix

### PR DESCRIPTION
**Pull request by cybergrind**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [ ] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [ ] I know that my PR will be merged only if it has tests and they pass  

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by mindlapse** [comment]
Hi @cybergrind, I tried this fix with an API 26 emulator (Android 8.0) and it should be fine there, although I am seeing some issues currently with the API 21 emulator (Android 5.0 - Lollipop) which is used in the Travis build - looking into it

**Comment by cybergrind** [comment]
@mindlapse yeah, I think that probably it would be great to find some minimal fix for Alipay, then we can go with other PRs. Unfortunately, I didn't get working version yet

**Comment by mindlapse** [comment]
The test does pass on API 26 without a problem (with Chrome).  With the API 21, the emulator is using the built-in browser, which seems to be causing a problem with Appium and chromedriver - it seems that this is preventing Appium from seeing the contents of the modal.  I see a few possible options:

1) (If the issue is chrome vs built in) - Find a way to use Chrome with the emulator, so that Appium can see the modal during the test
2) Run the tests using a newer version of Android (implying dropping support for API 21 / Lollipop)

**Comment by cybergrind** [comment]
@mindlapse  2 is fine by me if it will work on Travis

**Comment by mindlapse** [comment]
@cybergrind - I found a solution!  Please see this commit:

https://github.com/tipsi/tipsi-stripe/pull/497/commits/de5444618f2fa9fc18e61cf79ff6d2b6264a53e2

The problem was that I was using an emulator with Chrome, while Travis uses the default browser.  I've updated the selectors to use `content-desc` and the test is passing for both API 21 and API 26

**Comment by cybergrind** [comment]
@mindlapse that's great! It looks like on android we have different selectors depending on android version (probably because of uiautomator or something else). 
So `idFromText` doesn't work for Android 5 but works on Android 8. And `idFromAccessId` works fine for Android 5 and we don't need any changes in selectors in that case. 
Probably `content-desc` is the best common discriminator in that case.

**Comment by cybergrind** [comment]
@mindlapse this branch has semi-stable Android tests.
I'm not sure that we can get DEFAULT_IOS running on Travis looks like it always timeouts.

**Comment by fbartho** [comment]
@mindlapse -- is this PR already included or replaced in the 8.0 Release? If so, should we close this PR?

**Comment by mindlapse** [comment]
Closing as all changes related to this are in #532 (although it's still not fully fixed - a new issue can be logged for that test case)

**Pull request closed without merging**
