### PR TITLE
[5.2.4] Add missing placeholder fields to iOS <PaymentCardTextField />

### LINKED ISSUE #284: <PaymentCardTextField> , numberPlaceholder attribute support only for android , not supported for IOS
I have checked this component in both android and IOS devices. Then I found '**numberPlaceholder**' attribute not support for IOS devices.
<PaymentCardTextField
                 style={styles.field}
                 disabled={false}
                 onParamsChange={this.handleFieldParamsChange}
                 numberPlaceholder={'0000 0000 0000 0000'}
               />

### LINKED ISSUE #294: React Native link failure tipsi-stripe@5.2.1
```
rnpm-install info Platform 'ios' module tipsi-stripe is already linked
rnpm-install info Platform 'android' module tipsi-stripe is already linked
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x007fab24035b20> (NoMethodError)
Did you mean?  to_s
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from node_modules/tipsi-stripe/scripts/post-link-ios.rb:17:in `<main>'

```

### PR DESCRIPTION
**Pull request by erikdstock**
Fixes #284  
Following the pattern of the rest of this component, this pr adds accessor methods to the TPSCardField.m which simply forward these properties onto the  Stripe SDK field.

### CODE REVIEW

**Comment by isnifer** [comment]
image
image

**Comment by isnifer** [comment]
image
image

**Comment by erikdstock** [comment]
Hi @isnifer- Is there anything I can do to help get this ready for merge?

**Comment by isnifer** [comment]
@erikdstock yeah, just need to fix e2e-test for an Android :)

**Comment by isnifer** [comment]
@erikdstock first of all, do `git pull -r` in your branch. iOS test works fine

**Comment by cybergrind** [comment]
@erikdstock thank you for your contribution

**Pull request merged**
