### PR TITLE
[4.6.4] Allow type to be specified on paymentSummaryItems

### PR DESCRIPTION
**Pull request by idris**
You can specify `pending`, otherwise it'll be set to `final`

Apple documentation: https://developer.apple.com/documentation/passkit/pkpaymentsummaryitem

### CODE REVIEW

**Comment by isnifer** [comment]
Hi, @idris you need to update also this one https://github.com/tipsi/tipsi-stripe/blob/master/src/utils/types.js#L16

**Comment by idris** [comment]
@isnifer thanks.  I updated it but the tests are still failing.  Any ideas?

**Comment by isnifer** [comment]
@idris when we will merge 4.6.3, you will rebase over `master` and it should be fixed (Stripe web page for tests payments via Sources has changed)

**Comment by isnifer** [comment]
@idris please, rebase over master

**Comment by isnifer** [comment]
@densa please, take a look

**Comment by idris** [comment]
@isnifer I rebased, but CI is still failing 😢

**Comment by idris** [comment]
@densa @isnifer tests are passing now 💯

**Comment by isnifer** [comment]
@idris Nice. My teammate need to take a look

**Comment by idris** [comment]
@isnifer this is approved.  Can it be merged/released now?

**Pull request merged**
