### PR TITLE
add Japanese transalation for Android

### PR DESCRIPTION
**Pull request by acro5piano**
## Proposed changes

Added Japanese translation for Android. My PR for the comment: https://github.com/tipsi/tipsi-stripe/issues/97#issuecomment-480642277

## Types of changes

- [ ] Bugfix (a non-breaking change which fixes an issue)  
- [x] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist

- [ ] I have added tests that prove my fix is useful or that my feature works 
- [x] I have added necessary documentation (if appropriate)  
- [x] I know that my PR will be merged only if it has tests and they pass  

## Further comments

Thank you for the amazing library.

### CODE REVIEW

**Comment by cybergrind** [comment]
@acro5piano may I ask you to rebase PR onto master, please? We rolled a quite big update and I will be happy to merge it after the rebase

**Comment by acro5piano** [comment]
@cybergrind Thanks for checking it. Instead rebase I've replace the original branch and force-pushed.

**Comment by cybergrind** [comment]
@acro5piano thank you, published in 8.0.1

**Comment by acro5piano** [comment]
@cybergrind Thank you for the great library!

**Pull request merged**
