### PR TITLE
Update usage.html

### PR DESCRIPTION
**Pull request by acatalina**
Broken link to google developers info

## Proposed changes
Fix broken link on docs to google developers info

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [x] I have added necessary documentation (if appropriate)  
- [ ] I know that my PR will be merged only if it has tests and they pass  

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by isnifer** [comment]
@acatalina Hi! Thank for the PR. `docs` dir is autogenerated as described in README. Please, edit https://github.com/tipsi/tipsi-stripe/blob/master/website/docs-md/usage.md file and follow guide to generate docs in `README.MD`

**Comment by acatalina** [comment]
@isnifer so sorry! LoL can't believe I didn't see that on the readme hehe just updated properly I believe :)

**Comment by isnifer** [comment]
@acatalina will be merged today)

**Comment by acatalina** [comment]
Still broken the link :(

**Comment by cybergrind** [comment]
hi @acatalina . Merged, thank you for reminding

**Pull request merged**
