### PR TITLE
Fix NoClassDefFoundError by bumping to SDK26/Play 11

### PR DESCRIPTION
**Pull request by tonyhb**
Bumping to RN 0.49.3 meant that we had to upgrade tipsi-stripe from 2.x to 3.x.

This, in turn, meant bumping the build tools to 26.0.1 to match both Lottie and to build Tipsi-Stripe.

The only way for tipsi-stripe to work is to bump the build tools to 26.0.1 and to incorporate the latest play-services-wallet (11.4.2).

This fixes a relapse of issue #18.

### CODE REVIEW

**Comment by isnifer** [comment]
@tonyhb you forgot to update Travis scripts

**Comment by tonyhb** [comment]
Ah, sorry.  Thanks for the heads up isnifer.  Added to my to do list, will probably take a look monday AM.

**Comment by tonyhb** [comment]
Legit can't get travis to install new SDKs - it fails saying licenses haven't been accepted, even when I try the travis workarounds.  Any tips?

**Comment by cybergrind** [comment]
@tonyhb could you please try to install all required versions of `build-tools`. You were on the right way with your previous commits but you've put wrong version (26 instead of 25).

I did that in https://travis-ci.org/tipsi/tipsi-stripe/jobs/293843050:
```
    yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.1"
    yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.2"
    yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.0.3"
    yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.2.3"
    yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;25.2.5"
```
So you just need to find required versions, cause I put every version here and that isn't good enough

**Comment by isnifer** [comment]
So, @tonyhb I've reviewed you PR. You can't just drop support for build-tools@25, cause some of the components use this version. I returned `- build-tools-25.0.0` and build became successful.

**Comment by maitham1** [comment]
is thus merged ????????

**Comment by maitham1** [comment]
Can we merge this please ???

**Comment by isnifer** [comment]
@maitham1 on the next week

**Comment by maitham1** [comment]
Still waiting for this guys? When forking tonyhb   repos I get an installation error ?

**Comment by isnifer** [comment]
Already landed

**Pull request closed without merging**
