### PR TITLE
AndroidX support for RN 0.60 or newer

### PR DESCRIPTION
**Pull request by fabriziomoscon**
## Proposed changes
This changes fix Android build with RN 0.60 and AndroidX.

## Types of changes
- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
Tests needs to be fixed on the base `experimental` branch. This PR doesn't address the failures on the base branch.

### CODE REVIEW

**Comment by leogoesger** [comment]
The newer version of tipsi-stripe already have all those changes.

**Comment by fabriziomoscon** [comment]
Hi @leogoesger in the current master AndroidX is not used - as far as i can tell - , neither in v8.0.0 branch.
Please could you help me to see in which branch can I find a version compatible with AndroidX?

**Comment by fabriziomoscon** [comment]
@leogoesger Please could you help me to see in which branch can I find a version compatible with AndroidX?

**Comment by fbartho** [comment]
This might be important for us @robertmurray

**Pull request closed without merging**
