### PR TITLE
Add Apple Pay setup with tests

### PR DESCRIPTION
**Pull request by dmytrozavgorodniy**
Fix for #40

### CODE REVIEW

**Comment by itsmepetrov** [comment]
Looks good to merge

**Comment by jsierles** [comment]
Why was the promise removed from `openApplePaySetup`? Is there a way to know when Apple Pay setup has finished?

**Comment by dmytrozavgorodniy** [comment]
Hi @jsierles, we can't know for sure, when Apple Pay setup has finished. From PassKit framework docs we have one function, which open Apple Pay setup:
```
func openPaymentSetup()

// Discussion
// Use this method to move users to the interface for adding credit cards.
// This method will transfer control to the Wallet app on iPhone or to the Settings app on iPad.
// On devices that do not support Apple Pay, this method does nothing.
```

PassKit framework doesn't give any completion callback for us. In some cases we can wait, until iOS application will enter foreground, after this call (`openApplePaySetup`), but we worry about unnecessary callbacks in this case.

**Comment by jsierles** [comment]
Thanks. I'm also using the foreground check. It works, and I figure such callbacks are not expensive.

**Comment by dmytrozavgorodniy** [comment]
We can add it to tipsi-stripe, but it will work like:
– on iOS simulator it will resolve Promise immediately
– on iOS device we will wait until iOS application will enter foreground and then it will resolve Promise
@jsierles to make sense?

How do you think, in which case we should reject Promise?

**Comment by jsierles** [comment]
Thinking about it more, I think it would be best just to mention this in docs and not directly implement. In my case, I'm already using app state for other things, so wouldn't necessarily want this library responding to app state on my behalf.

**Pull request merged**
