### PR TITLE
Add email address to Google/Android pay

### LINKED ISSUE #278: Email address not available in Google Pay
Google pay currently only gives you back the card token and optionally basic billing address and full shipping address as options.

Email address is always available as Google Pay is tied to an email address so it should be there always, it's as vital and as available as the card token so why not.

(Note: This is an issue to document the pull request I'm making so please don't jump right in and fix it)

### PR DESCRIPTION
**Pull request by shokimble**
I have added email address to extras in Google and Android pay. Not properly tested in Android pay but it's the exact same code just in a different module so can't see why it wouldn't work.

Note: No option added for it. The email is always available, we're not changing the UX by adding email.

Fixes #278

### CODE REVIEW

**Comment by isnifer** [comment]
@shokimble Hi! Now I know how to do your PR correct. You should pass an option `email_required` to a payment method like here — https://github.com/tipsi/tipsi-stripe/pull/353.

**Comment by shokimble** [comment]
As I mentioned earlier it's not an option for the user so I don't see the point in having it as an option for the developer. 

Either way the user is prompted for an email address so it will be returned. The only thing the option might do is allow the developer to ignore a field that they can ignore anyway.

**Comment by isnifer** [comment]
@shokimble default value is `false` https://developers.google.com/android/reference/com/google/android/gms/wallet/PaymentDataRequest.Builder#setEmailRequired(boolean)

Don't see any reason to do it differently. If there is a method on google pay side, we should provide the same method (false by default).

**Comment by shokimble** [comment]
It's almost a year and I cannot believe this basic change is not merged. There's no argument against it. It keeps the API consistent which is the most important thing.

It's little details like this that make the RN community look like a joke.

Sorry this rant is not meant to be an attack on any individual but when there isn't even a functional payments system it makes RN on the whole look stupid.

**Comment by cybergrind** [comment]
Hey @shokimble 
1) this PR should be rebased, should have no conflicts and pass tests
2) Because this library has the intention to provide the same API for both platforms, I do believe that additional option should be involved (`email_required`) at least to be compatible with existent flows and to give an option to handle this for IOS platform.

Regarding your complaints: I'm really sorry that it takes that much time but this PR has issues to be addressed before the merge.

**Comment by shokimble** [comment]
@cybergrind good answer. You should work in developer/public relations :)

I'm addressing those issues now and will re-submit.

**Comment by shokimble** [comment]
Closing in favour of:

https://github.com/tipsi/tipsi-stripe/pull/469

**Pull request closed without merging**
