### PR TITLE
[3.8.0] Link Stripe pod dependency to TPSStripe target via cocoapods

### PR DESCRIPTION
**Pull request by dmytrozavgorodniy**

### CODE REVIEW

**Comment by dmytrozavgorodniy** [comment]
@isnifer we also should upgrade migration guide and we are done, please check implementation

**Comment by brianhiss** [comment]
@dmytrozavgorodniy I've tested your branch, everything seems to work. I've cleaned and built twice to make sure, no issues building, quick applications tests allow adding credit cards.

My test steps:
- `react-native unlink tipsi-stripe`
- `yarn add https://github.com/tipsi/tipsi-stripe.git#feature/link-stripe-to-tpsstripe`
- `react-native link tipsi-stripe`
- Manually edited my `Podfile` with the new `TPSStripe` target
- Cleaned out `Derived Data` folder and ran build.

Thank you for taking a closer look. The new docs site looks great!

**Comment by isnifer** [comment]
@brianhiss awesome, thank you. We will release it today as 3.8.0

**Comment by dmytrozavgorodniy** [comment]
@brianhiss good news, thanks!

**Comment by dmytrozavgorodniy** [comment]
@brianhiss do you use `use_frameworks!` flag in your `Podfile`?

**Comment by brianhiss** [comment]
No, no Swift Frameworks in my setup, so no. `#use_frameworks!`

**Comment by dmytrozavgorodniy** [comment]
Cool! In our app we are using `#use_frameworks!` and it works well too. @isnifer I think we are ready to review and merge.

**Comment by brianhiss** [comment]
@dmytrozavgorodniy @isnifer I am now seeing fatal errors of `'Stripe/Stripe.h' file not found.`

I was wondering why `3.8.0` stopped working for me and realized I added a new NPM package `yarn add react-native-firebase@3.0.3` to upgrade `react-native-firebase@3.0.2`. 

I have figured out that I have to run `react-native link tipsi-stripe` now every time after I install a new NPM package with this fix. I am not sure why. I did not have the same issues with NPM packages with my pull request: https://github.com/tipsi/tipsi-stripe/pull/132.

Are you guys seeing the same thing on your end? Or is this just in my setup?

**Comment by dmytrozavgorodniy** [comment]
@brianhiss We was tried to reproduce your issue with next steps:
1. Create base react native app
2. Install react-native-firebase 3.0.2. Add `pod 'Firebase/Core', '4.0.4'` to Podfile. Link react-native-firebase.
3. Build success
4. Install tipsi-stripe 3.8.0. Add `pod 'Stripe', '10.1.0'` and another tipsi-stripe configs to Podfile. Link tipsi-stripe.
5. Build success
6. Update react-native-firebase to 3.0.3 (npm install --save react-native-firebase@3.0.3)
7. Build success

It works for us. Maybe you can provide more information?

**Comment by dmytrozavgorodniy** [comment]
What changed when you upgrade from react-native-firebase from 3.0.2 to 3.0.3, do you diff maybe?

**Comment by brianhiss** [comment]
@dmytrozavgorodniy I was able to replicate this Fatal Error on a new `react-native init Example` project as well. With the standard React Native `.gitignore`, nothing but `package.json` changed.

Same steps as you above, but when you add the Firebase Pod, make sure you add not just the core, but the `pod 'Firebase/Storage'`, this is what downloads `gRPC` and a bunch of other dependencies.

1. `react-native init Example`
2. `yarn add react-native-firebase@3.0.2`
3. `react-native link react-native-firebase`
4. `pod init`
5. Open `Podfile` and paste below:
```
# Use iOS 9 and above
platform :ios, '9.0'

# Specify Workspace
workspace 'Example'

target 'Example' do

  # Core is always required
  pod 'Firebase/Core' # includes Analytics

  # Optional Modules (https://firebase.google.com/docs/ios/setup)
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'

end
```
6. `pod install`
7. `yarn add tipsi-stripe@3.8.0`
8. Open `Podfile` and edit to below:
```
# Use iOS 9 and above
platform :ios, '9.0'

# Specify Workspace
workspace 'Example'

target 'Example' do

  # Stripe
  pod 'Stripe', '~> 10.1.0'

  # Core is always required
  pod 'Firebase/Core' # includes Analytics

  # Optional Modules (https://firebase.google.com/docs/ios/setup)
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'

end

target 'TPSStripe' do

    project '../node_modules/tipsi-stripe/ios/TPSStripe'
    pod 'Stripe', '~> 10.1.0'

end
```
9. `react-native link tipsi-stripe`
10. Build: `Success`
11. `yarn add react-native-firebase@3.0.3`
12. Build: `Fatal Error: 'Stripe/Stripe.h' file not found.`

**Comment by dmytrozavgorodniy** [comment]
@brianhiss Hi, could you please check our PR (#141), we fixed `HEADER_SEARCH_PATHS` for iOS project. We are using your dependencies in our example and we hope this helps you. We will be grateful if you provide your feedback.

**Pull request merged**
