### PR TITLE
WIP - Fix reject not called

### PR DESCRIPTION
**Pull request by zhigang1992**
## Proposed changes
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. 
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [ ] I know that my PR will be merged only if it has tests and they pass  

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by zhigang1992** [comment]
Wasn’t sure on why do we need to hold the reference and call a different method. Can we just call reject directly?
I’m seeing that other places having the same issue and I’ve not gone through them yet.

**Comment by cybergrind** [comment]
@zhigang1992 can you add tests for your fix?

**Comment by zhigang1992** [comment]
@cybergrind It doesn't look your guys have unit test setup for iOS, can you show me how to add these tests?

**Comment by cybergrind** [comment]
@zhigang1992 we're doing most our tests for tipsi-stripe as integration tests. They can be found here: https://github.com/tipsi/tipsi-stripe/tree/master/example/__tests__
In general, I'm not sure that proper unit tests are possible for RN right now (at least I'm not aware of it)
Usually, if there is a bug it is possible to demonstrate it in integration tests.

**Comment by zhigang1992** [comment]
@cybergrind it seems like our integration tests currently only test happy paths. Also for some reason, I'm having trouble successfully running all tests. 😭 

Should we start creating error UIs for the example?

**Pull request closed without merging**
