### PR TITLE
[iOS] Bank Accounts support

### PR DESCRIPTION
**Pull request by dmytrozavgorodniy**

### CODE REVIEW

**Comment by dmytrozavgorodniy** [comment]
@itsmepetrov ready for code review, please check

**Comment by MobiusHorizons** [comment]
working on an app that needs this, thanks for the work!!

**Comment by rheilgm** [comment]
waiting for this feature too, hope this could be merge already

**Comment by itsmepetrov** [comment]
@dmytrozavgorodniy please update version to `3.1.0`

**Comment by dmytrozavgorodniy** [comment]
@itsmepetrov ready to merge, please review last time

**Comment by MobiusHorizons** [comment]
+1

**Comment by isnifer** [comment]
@itsmepetrov your turn

**Comment by itsmepetrov** [comment]
Looks good to merge

**Comment by MobiusHorizons** [comment]
awesome, thanks guys!!

**Pull request merged**
