### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by emlynmac**
## Proposed changes
Adds typescript language definitions for the non-deprecated components

- [ ] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

### CODE REVIEW

**Comment by cybergrind** [comment]
hey @emlynmac. it is great to have your PR but we want to see tests for a new functionality. There is already PR with TS types here #264 but it doesn't pass tests on Travis. 
So it would be great to see some tests

**Comment by emlynmac** [comment]
What is failing on travis and why? 
Technically, this doesn't add any new functionality, it just enables TS users to access the current functionality.
Could you specify what sort of tests you'd like to see?

**Comment by cybergrind** [comment]
@emlynmac right now we don't use TS at all in our application. 
This means that if something breaks in code (for example if we change API signature) we won't notice this and it will bad for TS users and us too. TS users will do everything ok typewise but get js errors, we will get a new issue about it.

So, ideally, we'd like to see a set of TS tests that will prevent such a situation. It can be a TS application (like we did for regular js https://github.com/tipsi/tipsi-stripe/tree/master/example) or any other appropriate way.

**Comment by emlynmac** [comment]
understood. I think for now I'll leave this here and let the #264 PR play out.

**Comment by henrikra** [comment]
I have closed #264

**Comment by orta** [comment]
My commits added tests for the typescript types via `dtslint` - you can re-use those if you'd like: https://github.com/henrikra/tipsi-stripe/pull/1/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R9

**Comment by cybergrind** [comment]
@emlynmac I believe we can move forward with your PR
1. we need to add at least dtslint
2. please remove bitcoin, it was removed in most recent SDK version

**Comment by fbartho** [comment]
@cybergrind this PR Is super interesting to us. -- Do you have a sense as to how much work it would take to get this into a shippable state?

**Comment by cybergrind** [comment]
@fbartho all PRs are blocked by issues with CI, so there is no ETA for this PR.

This particular PR doesn't have any tests so if you really want to have it merged some tests must be added: we don't use TS at all, so it will be quite hard to maintain the code without tests.

**Comment by fbartho** [comment]
@emlynmac I super appreciate this PR! (I meant to say that in my last message)

@cybergrind -- I hear you. Hopefully once the CI issues are resolved by somebody / @mindlapse and we get past the European SCA (Strong Customer Authentication Deadline), then we can start to talk about what it would take to get useful tests for this. (I'm not sure what kind of testing would work for validating side-car typescript types against JavaScript). -- My team uses TypeScript, so we're pretty invested in contributing back to libraries we need to rely on!

**Comment by fbartho** [comment]
Some further as-yet-untested typedefs I spent some time establishing:
```typescript
	interface PaymentCardTextFieldNativeEvent {
		valid: boolean;
		params: {
			number: string;
			expMonth: string;
			expYear: string;
			cvc: string;
		};
	}
	interface PaymentCardTextFieldCommonProps {
		expirationPlaceholder?: string;
		numberPlaceholder?: string;
		cvcPlaceholder?: string;
		disabled?: boolean;

		onChange?: (params: PaymentCardTextFieldNativeEvent) => void;

		/** Deprecated */
		onParamsChange?: (
			valid: boolean,
			nativeEventParams: PaymentCardTextFieldNativeEvent["params"],
		) => void;

		style?: StyleProp<ViewStyle & { color?: string }>;
	}
	interface PaymentCardTextFieldIOSProps {
		cursorColor?: string;
		textErrorColor?: string;
		placeholderColor?: string;
		keyboardAppearance?: "default" | "light" | "dark";
	}
	interface PaymentCardTextFieldAndroidProps {
		setEnabled?: boolean;
		backgroundColor?: string;
		cardNumber?: string;
		expDate?: string;
		securityCode?: string;
	}

	class PaymentCardTextField extends Component<
		Omit<ViewProps, "style"> &
			PaymentCardTextFieldCommonProps &
			PaymentCardTextFieldIOSProps &
			PaymentCardTextFieldAndroidProps
	> {
		isFocused: () => boolean;
		focus: () => void;
		blur: () => void;
		setParams: (params: CardTokenParams) => void;
	}

	interface StripeNativeErrorDescription<Code extends StripeNativeErrorCode> {
		errorCode: Code | string;
		description?: string;
	}
	export const enum StripeNativeErrorCode {
		busy = "busy",
		cancelled = "cancelled",
		purchaseCancelled = "purchaseCancelled",
		sourceStatusCanceled = "sourceStatusCanceled",
		sourceStatusPending = "sourceStatusPending",
		sourceStatusFailed = "sourceStatusFailed",
		sourceStatusUnknown = "sourceStatusUnknown",
		deviceNotSupportsNativePay = "deviceNotSupportsNativePay",
		noPaymentRequest = "noPaymentRequest",
		noMerchantIdentifier = "noMerchantIdentifier",
		noAmount = "noAmount",
		parseResponse = "parseResponse",
		activityUnavailable = "activityUnavailable",
		playServicesUnavailable = "playServicesUnavailable",
		redirectCancelled = "redirectCancelled",
		redirectNoSource = "redirectNoSource",
		redirectWrongSourceId = "redirectWrongSourceId",
		redirectCancelledByUser = "redirectCancelledByUser",
		redirectFailed = "redirectFailed",

		// Description provided by stripe api
		api = "api",
		apiConnection = "apiConnection",
		redirectSpecific = "redirectSpecific",
		card = "card",
		invalidRequest = "invalidRequest",
		stripe = "stripe",
		rateLimit = "rateLimit",
		authentication = "authentication",
		permission = "permission",
	}
	const errorCodes: {
		[Code in StripeNativeErrorCode]: StripeNativeErrorDescription<Code>
	};

	export { PaymentCardTextField, errorCodes };
```

**Comment by fbartho** [comment]
Thanks for your contribution @emlynmac -- we're looking forward to integrating some sort of Typings in 8.1 -- since the base team doesn't use TypeScript I'm considering trying to write a tool to convert JSDoc comments into TypeScript -- do you have any feelings about this?

**Comment by emlynmac** [comment]
@fbartho I think I'm in no position to have an opinion on the inner workings of your team ;). What I would say is that I don't think it will help to make a JSDoc converter tool as I think you'll run into issues of specificity quickly. It really doesn't take too much to make a typing for your external API - the key is to keep it up to date. TypeScript really isn't that hard to pick up too - and can be added slowly with the rest of your code while leveraging type-safety as you go. I can't count the number of times that TS has prevented run-time errors for me....

**Comment by fbartho** [comment]
@emlynmac -- I should be clear, as an individual, I love TypeScript, and need this PR for my company's own app!

Above I was speaking as an OSS contributor. As I understand it, Tipsi does not use TypeScript. I just happen to be a contributor helping get the 8.0 release ready. I don't want to push TypeScript if Tipsi doesn't want it, but if we're including typings, we probably want some sort of automated validations that they still match the JS.

Do you have any advice on how to "verify" that JS changes don't break TypeScript Typings? I only have experience with projects that converted their code to TypeScript and changed their release process to compile to JS + Typings. I don't have experience with projects successfully maintaining sidecar typings files.

**Comment by orta** [comment]
This PR could add support for that - https://github.com/microsoft/TypeScript/pull/32372

Just spotted @Charliekenney23 add this lib to definitely typed - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38568 BTW

**Comment by mattdamon108** [comment]
I know it is quite a while. But, any progress for types?
I'd like to use this module but can't find a way to use a type in my project with typescript.

**Comment by Charliekenney23** [comment]
> I know it is quite a while. But, any progress for types?
> I'd like to use this module but can't find a way to use a type in my project with typescript.

@mattdamon108 We've forked this repo to added typings and fix tipsi/tipsi-stripe#408. We're using that for now.

https://github.com/lifeomic/tipsi-stripe
`yarn add @lifeomic/tipsi-stripe`

**Comment by mattdamon108** [comment]
@Charliekenney23 Thanks!

**Comment by ste00martin** [comment]
bump on this thread, are we getting type definitions?

**Comment by asurare** [comment]
Is there a reason to hold this pull request ?

**Comment by podotki** [comment]
Hi guys !

I share with you typing file I'm using, updated with the last **8.0.0-beta.10** version:
https://gist.github.com/podotki/f5b258b8d6d45ba5d1074f7e289eedee

It might be helpful...or not.

Cheers guys :)

**Comment by michaelbayday** [comment]
Very interested in this

**Comment by gjuoun** [comment]
any news?

**Pull request closed without merging**
