### PR TITLE
Fix 3D secure process

### PR DESCRIPTION
**Pull request by tlenclos**
This PR introduces some fixes for the 3D secure process
- Update stripe iOS sdk (11.2.0 to 13.0.1) and fix the redirect context as explained here https://github.com/tipsi/tipsi-stripe/issues/299#issuecomment-394247586 cc @verna1228 
- Fix other issues with bitcoin not supported by stripe anymore and the address format deprecation (see https://github.com/tipsi/tipsi-stripe/issues/301)
- Introduced a new parameter `createCardSource` to the method `paymentRequestWithCardForm` (iOS & Android) to create a source instead of a token (needed to get the 3D secure state of the card)

With these changes I was able to successfully check if the card needs a 3D secure (or force it) and then complete the redirection flow to charge the user, like so

```javascript
const cardResponse = await stripe.paymentRequestWithCardForm({
    createCardSource: true
});

if (
    cardResponse.card.three_d_secure === "recommended"
    || cardResponse.card.three_d_secure === "required"
) {
    const secure3dSourceResponse = await stripe.createSourceWithParams({
        type: "threeDSecure",
        amount: 1000,
        currency: "EUR",
        flow: "redirect",
        returnURL: "my-app://stripe-redirect",
        card: sourceId
    });
}
```

## TODO
- [ ] Review / test BC
- [ ] Update documentation
- [ ] Rebase on master

### CODE REVIEW

**Comment by Freddy03h** [comment]
It work well on iOS and Android, thank's !!!

**Comment by tlenclos** [comment]
I am glad it's also working well for you ! 
Hi @cybergrind, I would love your input on this as it's quite a lot to review may cause some BC

**Comment by cybergrind** [comment]
@tlenclos looks great. @isnifer I believe we need to fix IOS travis to be able to merge this request

**Comment by janicduplessis** [comment]
You probably want to update this too https://github.com/tipsi/tipsi-stripe/blob/master/scripts/post-link-ios.rb#L10

**Comment by isnifer** [comment]
@tlenclos `master` branch is fixed. You can `rebase` and test your work on the CI

**Comment by ratkus91** [comment]
When will this PR be merged?

**Comment by cybergrind** [comment]
@ratkus91 it should be rebased and have no tests errors

**Comment by cybergrind** [comment]
@tlenclos going to close this PR in favor of #389 
thank you for your time

**Pull request closed without merging**
