### PR TITLE
Add support for ApplePay delegate shipping method and contact changes

### PR DESCRIPTION
**Pull request by pagameba**
If you need to recalculate what is shown to the user when they select a shipping address or shipping method (updating tax and shipping costs, or changing available shipping options), there is no way currently to do this.  The PR adds the necessary delegate methods and triggers events up to JS land to allow this to happen.  The RCT bridge does not support sending closures or really anything complex so we store the completion closure on the manager itself and provide an update method that would be called inside an event handler in client code using the library.

### CODE REVIEW

**Comment by lewisf** [comment]
What's the status on this and is there anything I can do to push this along?

**Comment by pagameba** [comment]
probably needs a rebase to clean up the commit history and resolve the conflict, but it does work and I'm using it in a production app.

**Comment by lewisf** [comment]
it looks like the conflict is due to `ObsoleteApiPayFlowImpl.java` having been fully deprecated (and deleted) in master. Is there any chance that could be fixed and merged? I'm also happy to do that in another PR

**Comment by lewisf** [comment]
This also does not seem to push up street address. I'd love to add it to this PR if I can get push access to this branch

**Comment by pagameba** [comment]
I just left on vacation, I’ll have my computer next week and will add you

**Comment by lewisf** [comment]
@cybergrind if i resolve merge conflicts + have this include street do you think this will be mergeable?

also @pagameba i noticed you use `region` instead of `state`. this is however inconsistent with apple's docs -- would you be okay with changing it from `region` to `state`?

**Comment by pagameba** [comment]
@lewisf sorry for the long delay, I am now back from vacation!  Changing `region` to `state` is fine with me.  If you open up a PR against my fork, I'll be happy to merge it.  It would be nice to get this in as we've recently released the android version of our app and I really don't want to be running from a fork.

**Comment by lewisf** [comment]
@densa @sergeyzhukov sorry for the ping but having trouble getting eyes from a reviewer on this. i'm looking to put in work to get this ready to land against the latest -- are there any concerns you all have that need to be addressed?

**Comment by spencewine** [comment]
Hi, what's the status of resolving the open issues on this?

**Comment by pagameba** [comment]
Looks like it needs a rebase to fix some conflicts, other than that I'm not sure what is required.  I'll see if we have the cycles to rebase.

**Comment by spencewine** [comment]
So it looks like this isn't happening?

**Comment by lewisf** [comment]
Haven’t had a chance to look either. Have a fork that works. No sign from maintainers on what they want before merging yet...

**Pull request closed without merging**
