### PR TITLE
Fixing AndroidX Integration

### PR DESCRIPTION
**Pull request by IanArko**
## Proposed changes
These changes allow tipsi-stripe to build with the new AndroidX system.

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  

- [x] Bugfix (a non-breaking change which fixes an issue)  
- [ ] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [x] I know that my PR will be merged only if it has tests and they pass  

## Further comments
This is a pretty simple change, but it will fix the issues documented here:
https://github.com/tipsi/tipsi-stripe/issues/506

Even thought this issue was closed, it continues to be a problem, as I've observed members of the community trying to use other packages as this one doesn't work with newer versions of RN. 

Thank you!

### CODE REVIEW

**Comment by fbartho** [comment]
@IanArko -- this is super interesting. We're doing AndroidX with `npx jetify` in our `postinstall` right now. Do you think we should merge these changes into tipsi-stripe? 

This would be backwards incompatible with people who haven't upgraded to AndroidX -- any feelings @mindlapse?

**Comment by walkerdb** [comment]
+1 on this PR

In general the react-native community has been full-steam-ahead on AndroidX, since google has not released any updates to its deprecated support libs since 2018. 

Most libs create a new breaking version that adds in support, with clear statements in the readme that version `x` is for react-native >= 0.60.x and `x - 1` is for react-native <=0.59.x. Even in that case the `jetifier -r` command lets folks use packages using AndroidX even in a 0.59 environment, so there are workarounds if needed.

**Comment by IanArko** [comment]
My big issue seemed to be that people weren't supporting tipsi-stripe as much as they were previously. I tried to find the issue again to link it here, but I couldn't, so my recollection is all I'll be able to give. It seemed like the community was in general supporting AndroidX to a great enough extent that people who are started using RN after 0.60 seem to not know to run the jetify command. It has been almost a year, and at this point, it seems like the right time.

**Comment by nadav-virdee** [comment]
Any update here? Is this fixed?

**Comment by FDiskas** [comment]
One more ping :)

**Comment by bramski** [comment]
@fbartho @cybergrind How can I help move this forward? I need to upgrade our app to 0.61 RN which means I need the AndroidX support.  Ripping out tipsi-stripe and replacing it with something else will likely be an equivalent amount of work.

**Comment by nadav-virdee** [comment]
I have been running -  npx jetify to solve this issue...

**Comment by fbartho** [comment]
@bramski Sorry for the delay in responding, this post got buried in pager duty emails. 

Is there a reason that jetify doesn’t work for you? There are plenty of packages that require it, so I haven’t felt the urgency to build a breaking release to support AndroidX directly. My app has been on AndroidX via jetify since May.

**Pull request closed without merging**
