### PR TITLE
WIP - Add method to collect shipping / delivery information

### LINKED ISSUE #332: Shipping address with .paymentRequestWithCardForm()
I noticed there is an optional field: `shipping_address_required` for `.paymentRequestWithApplePay()` and `.paymentRequestWithAndroidPay()`.

Is it possible to also have a shipping address with `.paymentRequestWithCardForm()`

### PR DESCRIPTION
**Pull request by yassinecc**
## Proposed changes
Add methods to collect shipping / delivery informations
Fixes #332

## Types of changes
What types of changes does your code introduce to `tipsi-stripe`?  
_Put an `x` in the boxes that apply_

- [ ] Bugfix (a non-breaking change which fixes an issue)  
- [x] New feature (a non-breaking change which adds functionality)  
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)  

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! Next steps are a reminder of what we are going to look at before merging your code._

- [ ] I have added tests that prove my fix is useful or that my feature works  
- [ ] I have added necessary documentation (if appropriate)  
- [x] I know that my PR will be merged only if it has tests and they pass  

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you choose the solution you did and what alternatives you considered.

### CODE REVIEW

**Comment by shubhamkes** [comment]
Any idea on how to send shipping information and payee's mail information while creating token?

**Comment by fbartho** [comment]
@yassinecc -- is this PR still relevant? We have a feature-release for 8.1 in about a month if you want to revive it. But if you're no longer interested we can close this PR.

I notice that this PR still needs an Android implementation.

**Comment by yassinecc** [comment]
Hello @fbartho this PR is still relevant and I would be happy to revive it but would probably need to confirm this approach of simply exposing UI components that collect shipping information

**Comment by fbartho** [comment]
We expose the PaymentTextfield Component, so it's not impossible. But doing this correctly is challenging to abstract across iOS & Android. I don't personally have a need for this, so I won't express an opinion either way. But if this is a valuable feature and doesn't add too much library surface area, we'd be happy to get it in to a feature release!

**Pull request closed without merging**
